import { IGames } from "../../../common/interface/games";

const PUBLIC_URL = process.env.PUBLIC_URL;

const List: IGames[] = [
  {
    id: 1,
    name: "Anaconda Wild 2",
    category: "new",
    img: `${PUBLIC_URL}/assets/game_icons/anaconda-wild-2.webp`,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Azteca Bonus Lines",
    category: "jackpots",
    img: `${PUBLIC_URL}/assets/game_icons/azteca-bonus-lines.webp`,
    isFavorite: false,
  },
  {
    id: 3,
    name: "Beach Life",
    category: "slots",
    img: `${PUBLIC_URL}/assets/game_icons/beach-life.webp`,
    isFavorite: false,
  },
  {
    id: 4,
    name: "Big Bad Wolf",
    category: "bingo",
    img: `${PUBLIC_URL}/assets/game_icons/big-bad-wolf.webp`,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Book of Egypt",
    category: "others",
    img: `${PUBLIC_URL}/assets/game_icons/book-of-egypt.webp`,
    isFavorite: false,
  },
  {
    id: 6,
    name: "Crocodile Blitz",
    category: "table games",
    img: `${PUBLIC_URL}/assets/game_icons/crocodile-blitz.webp`,
    isFavorite: false,
  },
  {
    id: 7,
    name: "Pride of Persia",
    category: "new",
    img: `${PUBLIC_URL}/assets/game_icons/pride-of-persia.webp`,
    isFavorite: false,
  },
  {
    id: 8,
    name: "Inca Jackpot",
    category: "jackpots",
    img: `${PUBLIC_URL}/assets/game_icons/inca-jackpot.webp`,
    isFavorite: false,
  },
  {
    id: 9,
    name: "Maya Jackpot",
    category: "others",
    img: `${PUBLIC_URL}/assets/game_icons/maya-jackpot.webp`,
    isFavorite: false,
  },
  {
    id: 10,
    name: "Pirates Power",
    category: "bingo",
    img: `${PUBLIC_URL}/assets/game_icons/pirates-power.webp`,
    isFavorite: false,
  },
  {
    id: 11,
    name: "Shaolin Crew",
    category: "others",
    img: `${PUBLIC_URL}/assets/game_icons/shaolin-crew.webp`,
    isFavorite: false,
  },
  {
    id: 12,
    name: "Sugar Rush",
    category: "new",
    img: `${PUBLIC_URL}/assets/game_icons/sugar-rush.webp`,
    isFavorite: false,
  },
  {
    id: 13,
    name: "Anaconda Wild 2",
    category: "table games",
    img: `${PUBLIC_URL}/assets/game_icons/anaconda-wild-2.webp`,
    isFavorite: false,
  },
  {
    id: 14,
    name: "Azteca Bonus Lines",
    category: "jackpots",
    img: `${PUBLIC_URL}/assets/game_icons/azteca-bonus-lines.webp`,
    isFavorite: false,
  },
  {
    id: 15,
    name: "Beach Life",
    category: "others",
    img: `${PUBLIC_URL}/assets/game_icons/beach-life.webp`,
    isFavorite: false,
  },
  {
    id: 16,
    name: "Big Bad Wolf",
    category: "slots",
    img: `${PUBLIC_URL}/assets/game_icons/big-bad-wolf.webp`,
    isFavorite: false,
  },
  {
    id: 17,
    name: "Book of Egypt",
    category: "bingo",
    img: `${PUBLIC_URL}/assets/game_icons/book-of-egypt.webp`,
    isFavorite: false,
  },
  {
    id: 18,
    name: "Crocodile Blitz",
    category: "new",
    img: `${PUBLIC_URL}/assets/game_icons/crocodile-blitz.webp`,
    isFavorite: false,
  },
  {
    id: 19,
    name: "Pride of Persia",
    category: "slots",
    img: `${PUBLIC_URL}/assets/game_icons/pride-of-persia.webp`,
    isFavorite: false,
  },
  {
    id: 20,
    name: "Inca Jackpot",
    category: "jackpots",
    img: `${PUBLIC_URL}/assets/game_icons/inca-jackpot.webp`,
    isFavorite: false,
  },
  {
    id: 21,
    name: "Maya Jackpot",
    category: "jackpots",
    img: `${PUBLIC_URL}/assets/game_icons/maya-jackpot.webp`,
    isFavorite: false,
  },
  {
    id: 22,
    name: "Pirates Power",
    category: "new",
    img: `${PUBLIC_URL}/assets/game_icons/pirates-power.webp`,
    isFavorite: false,
  },
  {
    id: 23,
    name: "Shaolin Crew",
    category: "others",
    img: `${PUBLIC_URL}/assets/game_icons/shaolin-crew.webp`,
    isFavorite: false,
  },
  {
    id: 24,
    name: "Sugar Rush",
    category: "others",
    img: `${PUBLIC_URL}/assets/game_icons/sugar-rush.webp`,
    isFavorite: false,
  },
];

export default List;
